baseurl = "http://localhost:1313/"
uglyurls = true
relativeURLs=false
languageCode = "zh-cn"
title = "Knative学习笔记"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
preserveTaxonomyNames = true
disablePathToLower = true

# Enable Google Analytics by entering your tracking id
googleAnalytics = "c7442f5794ea2abb71c6ff05dc0b8779"

[params]
	# General information
	author = "敖小剑"
	keywords = "knative,学习笔记,敖小剑"
	description = "Knative是Google新推出来的Serverless平台。"
	copyright = "版权所有，转载请注明出处"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/skyao/learning-knative"
	
	version = ""
	logo = "images/logo.png"
	favicon = ""
	
	permalink = "#"
	
	# reward button, comment this to disable it
	reward = true
	
	# Custom assets
	custom_css = []
	custom_js  = []
	
	# Syntax highlighting theme
	highlight_css  = ""
	
	[params.palette]
		primary = "red"
		accent  = "teal"
	
	[params.font]
		text = "Ubuntu"
		code = "Ubuntu Mono"

[social]
	twitter = ""
	github  = "skyao"
	email   = "aoxiaojian@gmail.com"


[[menu.main]]
	name   = "前言"
	url    = "/"
	weight = 1

[[menu.main]]
	name   = "介绍"
	identifier = "introduction"
	url    = "/introduction/"
	weight = 100

[[menu.main]]
	name   = "Build模块"
	identifier = "build"
	url    = "/build/"
	weight = 200

[[menu.main]]
	name   = "Serving模块"
	identifier = "serving"
	url    = "/serving/"
	weight = 300

[[menu.main]]
	name   = "Serving概述"
	identifier = "serving-overview"
	parent = "serving"
	url    = "/serving/overview/"
	weight = 310

[[menu.main]]
	name   = "Serving API"
	identifier = "serving-api"
	parent = "serving"
	url    = "/serving/api/"
	weight = 320

[[menu.main]]
	name   = "Serving Scaling"
	identifier = "serving-scaling"
	parent = "serving"
	url    = "/serving/scaling/"
	weight = 330

[[menu.main]]
	name   = "Runtime Contract"
	identifier = "runtime-contract"
	parent = "serving"
	url    = "/serving/runtime-contract/"
	weight = 350

[[menu.main]]
	name   = "Eventing模块"
	identifier = "eventing"
	url    = "/eventing/"
	weight = 400

[[menu.main]]
	name   = "Event Source"
	identifier = "eventing-source"
	parent = "eventing"
	url    = "/eventing/source/"
	weight = 410

[[menu.main]]
	name   = "Event Registry"
	identifier = "eventing-registry"
	parent = "eventing"
	url    = "/eventing/registry/"
	weight = 430

[[menu.main]]
	name   = "Broker和Trigger"
	identifier = "eventing-broker"
	parent = "eventing"
	url    = "/eventing/broker/"
	weight = 440

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true


